name: Run Tests

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and run Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: false
        load: true
        tags: cryptkeeper-test:latest

    - name: Run tests
      run: docker run cryptkeeper-test:latest
