name: Update Homebrew Formula

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Homebrew tap repository
        uses: actions/checkout@v2
        with:
          repository: sunny-b/homebrew-cryptkeeper
          token: ${{ secrets.HOMEBREW_TOKEN }}
          path: homebrew-tap

      - name: Update the Homebrew tap repository
        run: |
          cd homebrew-tap
          git checkout -b update-${{ github.event.release.tag_name }}
          ./update-homebrew.sh
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update homebrew formula to version ${{ github.event.release.tag_name }}"
          git push origin update-${{ github.event.release.tag_name }}