name: Update Homebrew Formula

on:
  release:
    types: [created]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Homebrew tap repository
        uses: actions/checkout@v2
        with:
          repository: sunny-b/homebrew-cryptkeeper
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run the update script
        run: ./update-homebrew.sh