name: Update Homebrew Formula

on:
  release:
    types: [created]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Homebrew tap repository
        uses: actions/checkout@v2
        with:
          repository: sunny-b/homebrew-cryptkeeper
          token: ${{ secrets.HOMEBREW_TOKEN }}
          path: homebrew-tap

      - name: Create new branch
        run: |
          cd homebrew-tap
          git checkout -b update-${{ github.event.release.tag_name }}

      - name: Run the update script
        run: |
          cd homebrew-tap
          ./update-homebrew.sh

      - name: Push changes
        run: |
          cd homebrew-tap
          git push origin update-${{ github.event.release.tag_name }}   

      - name: Create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.HOMEBREW_TOKEN }}
          path: 'homebrew-tap'
          title: 'New Homebrew Formula version'
          body: 'Updating version of homebrew formula'
          branch: update-${{ github.event.release.tag_name }}
          base: 'main'